apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samplelog
  name: samplelog
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samplelog
  template:
    metadata:
      labels:
        app: samplelog
    spec:
      containers:
      - image: acrann.azurecr.io/sample-log
        name: samplelog
        # imagePullPolicy: Never
      restartPolicy: OnFailure
